version: '3.8'  # Specifies the version of Docker Compose

services:
  go-date-time-app:
    image: praashantyadav/go-date-time-app:latest  # Specifies the Docker image to use
    container_name: go-date-time-app  # Optional: Sets the container name
    ports:
      - "8080:8080"  # Maps port 8080 on the host to port 8080 on the container
    environment:
      - ENV=production  # Set any environment variables required by the app
    restart: always  # Ensures the container restarts on failure
    # volumes:
    #   - ./path/to/local/dir:/path/in/container  # Uncomment and modify if you need to mount volumes
